/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swingnotepad;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JTextArea;
import javax.swing.text.Caret;

/**
 *
 * @author edutilos
 */
public class ReplaceGUI extends javax.swing.JFrame {

    private JTextArea areaDisplay ; 
    
    /**
     * Creates new form FindGUI
     */
    public ReplaceGUI(JTextArea areaDisplay) {
        this.areaDisplay = areaDisplay ; 
        initComponents();
        registerEvents(); 
    }
    
        private int currentIndex; 
    private String token; 
    private String content; 
    int mark = -1; 
    Pattern p ; 
    Matcher m; 
    
    private void prepareContent() {
   
       token = editFind.getText();    
       content = areaDisplay.getText(); 
       if(!cbMatchCase.isSelected()) {
           token = token.toLowerCase(); 
           content = content.toLowerCase(); 
       } 
       
          p = Pattern.compile(token); 
       m = p.matcher(content); 
    }
    
    
    private void registerEvents() {
       
        prepareContent();
        
        btnFind.addActionListener(l-> {
           onBtnFind();
        });
        
        btnCancel.addActionListener(l-> {
             onBtnCancel();
        }); 
      
   
        cbMatchCase.addChangeListener(l-> {
            prepareContent();
        });
        
        
        btnReplace.addActionListener(l-> {
             onBtnReplace();
        }); 
        
        btnReplaceAll.addActionListener(l-> {
            onBtnReplaceAll();
        }); 
    }


    
    
    private void onBtnReplace() {
        prepareContent();
        StringBuilder builder = new StringBuilder(areaDisplay.getText()); 
        int start = areaDisplay.getSelectionStart(); 
        int end = areaDisplay.getSelectionEnd(); 
        if(start == end || editReplace.getText().isEmpty()) return ; 
        builder.replace(start , end , editReplace.getText());
        System.out.println(builder.toString());
        areaDisplay.setText(builder.toString());
    }
    
    
    private void onBtnReplaceAll() {
        prepareContent(); 
        if(editReplace.getText().isEmpty()) return ; 
        //System.out.println(edit.toString());
        content = areaDisplay.getText(); 
        token = editFind.getText(); 
        if(cbMatchCase.isSelected())
        content = content.replaceAll(token, editReplace.getText()); 
        else 
            content = content.replaceAll("(?i)"+token, editReplace.getText()); 
        areaDisplay.setText(content); 
    }
    
    
    private void onBtnFind() {
        prepareContent(); 
        if(mark!= -1) areaDisplay.setCaretPosition(mark);
        mark = areaDisplay.getCaretPosition(); 
        
        System.out.println("mark = " + mark);
    //   currentIndex = mark; 
     
           
      findForwards();
       
    }
    
    
    private void findForwards() {
       if(m.find(mark)) {
           areaDisplay.setSelectionStart(m.start());
           areaDisplay.setSelectionEnd(m.end()); 
           mark = m.end(); 
           //areaDisplay.setCaretPosition(mark);
       } else {
//           if(mark < content.length())
//           mark += 1 ; 
       }
    }
 
    
    
    private void onBtnCancel() {
        this.dispose();
    }
    
    public String getFindToken() {
        return editFind.getText(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupFindDirection = new javax.swing.ButtonGroup();
        lblFind = new javax.swing.JLabel();
        editFind = new javax.swing.JTextField();
        btnReplace = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        cbMatchCase = new javax.swing.JCheckBox();
        lblReplace = new javax.swing.JLabel();
        editReplace = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnReplaceAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find");

        lblFind.setText("Find What:");

        editFind.setColumns(10);

        btnReplace.setText("Replace");

        btnFind.setText("Find Next");

        cbMatchCase.setText("Match Case");

        lblReplace.setText("Replace With:");

        editReplace.setColumns(10);

        btnCancel.setText("Cancel");

        btnReplaceAll.setText("Replace All");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbMatchCase)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblReplace)
                            .addGap(18, 18, 18)
                            .addComponent(editReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblFind)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editFind, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReplaceAll, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btnReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFind)
                    .addComponent(editFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReplace)
                    .addComponent(lblReplace)
                    .addComponent(editReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnReplaceAll)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(cbMatchCase))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FindGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FindGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FindGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FindGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FindGUI(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReplace;
    private javax.swing.JButton btnReplaceAll;
    private javax.swing.JCheckBox cbMatchCase;
    private javax.swing.JTextField editFind;
    private javax.swing.JTextField editReplace;
    private javax.swing.ButtonGroup groupFindDirection;
    private javax.swing.JLabel lblFind;
    private javax.swing.JLabel lblReplace;
    // End of variables declaration//GEN-END:variables
}
